package(default_visibility = ["//visibility:public"])

exports_files([
    "deployment-production.yaml",
    "deployment-canary.yaml",
    "service.yaml",
    "ingress.yaml",
    "service-monitor.yaml",
])
