apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shorten
    version: v1
  name: url-shorten-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shorten
      version: v1
  template:
    metadata:
      labels:
        app: url-shorten
        version: v1
    spec:
      containers:
        - image: url-shorten-production:latest
          name: url-shorten-production
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0