apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shorten
  name: url-shorten
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: url-shorten
  sessionAffinity: None
  type: ClusterIP
