apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shorten-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: url-shorten
  endpoints:
  - port: http