namespaceOverride: "metrics-monitoring"
prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchLabels:
        metrics-monitoring: target
grafana:
  namespaceOverride: "metrics-monitoring"
kube-state-metrics:  
  namespaceOverride: "metrics-monitoring"
prometheus-node-exporter:
  namespaceOverride: "metrics-monitoring"
